### ISSUE TITLE
a better way to split values separated by ';' in a single column value (pandas module)

### ISSUE THREAD

**Issue by Arjun1372000** [Arjun1372000/beginner_data_project#3]
https://github.com/Arjun1372000/beginner_data_project/blame/df881fe0e23bf0967168485f1efb137645b606bc/data_project_beginner.py#L29C78-L29C78

**Comment by Arjun1372000** [comment]
from line 29

**Comment by MatterAndy** [comment]
I am not very experienced using Pandas, but looking at the code, I think some possible improvements could be:
- Remove the double loops for better readability
- Use .append() or .extend() instead of += to optimize the code slightly
- Avoid using _ as an element in a loop if that element is used
- Give a full name to the variable d for better readability
- Add some documentation about the input and output of the function

Some improved code might look like this:
```
# input: Pandas DataFrame
def split_column_values(data):
    data = data.dropna().values.tolist()
    lst = []
    for val in data:
        lst.extend(val[0].split(';'))
    return pd.Series(lst)
# output Pandas Series
```
I have not tested this code, so I might have made mistakes. I am also not the most experienced with Pandas or quick list manipulation in Python, so it can probably be simplified and optimized further. Still, I hope this helps!

**Comment by Arjun1372000** [comment]
Thank you for the suggestions.
You have really great ideas for efficient documentations, which I'm pretty bad at so really,
Thank you.

**Comment by Arjun1372000** [comment]
@Arjun1372000 dfcecd60af9cc0eaaafaa48cbe619d47ebba2a9f

It's better now!
